function saveElementsJson() {
    operationJson = {
        '"WebDBElements".Elements[1].elementId': adapterJSON.elements[0].elementId,
        '"WebDBElements".Elements[1].elementType': adapterJSON.elements[0].elementType,
        '"WebDBElements".Elements[1].elementName': adapterJSON.elements[0].elementName,
        '"WebDBElements".Elements[1].elementSize': adapterJSON.elements[0].elementSize,
        '"WebDBElements".Elements[1].elementMinSize': adapterJSON.elements[0].elementMinSize,
        '"WebDBElements".Elements[1].elementVerticalPosition': adapterJSON.elements[0].elementVerticalPosition,
        '"WebDBElements".Elements[1].elementHorizontalPosition': adapterJSON.elements[0].elementHorizontalPosition,
        '"WebDBElements".Elements[1].type': adapterJSON.elements[0].type,
        '"WebDBElements".Elements[1].display': adapterJSON.elements[0].display,
        '"WebDBElements".Elements[1].fontSize': adapterJSON.elements[0].fontSize,

        '"WebDBElements".Elements[2].elementId': adapterJSON.elements[1].elementId,
        '"WebDBElements".Elements[2].elementType': adapterJSON.elements[1].elementType,
        '"WebDBElements".Elements[2].elementName': adapterJSON.elements[1].elementName,
        '"WebDBElements".Elements[2].elementSize': adapterJSON.elements[1].elementSize,
        '"WebDBElements".Elements[2].elementMinSize': adapterJSON.elements[1].elementMinSize,
        '"WebDBElements".Elements[2].elementVerticalPosition': adapterJSON.elements[1].elementVerticalPosition,
        '"WebDBElements".Elements[2].elementHorizontalPosition': adapterJSON.elements[1].elementHorizontalPosition,
        '"WebDBElements".Elements[2].type': adapterJSON.elements[1].type,
        '"WebDBElements".Elements[2].display': adapterJSON.elements[1].display,
        '"WebDBElements".Elements[2].fontSize': adapterJSON.elements[1].fontSize,

        '"WebDBElements".Elements[3].elementId': adapterJSON.elements[2].elementId,
        '"WebDBElements".Elements[3].elementType': adapterJSON.elements[2].elementType,
        '"WebDBElements".Elements[3].elementName': adapterJSON.elements[2].elementName,
        '"WebDBElements".Elements[3].elementSize': adapterJSON.elements[2].elementSize,
        '"WebDBElements".Elements[3].elementMinSize': adapterJSON.elements[2].elementMinSize,
        '"WebDBElements".Elements[3].elementVerticalPosition': adapterJSON.elements[2].elementVerticalPosition,
        '"WebDBElements".Elements[3].elementHorizontalPosition': adapterJSON.elements[2].elementHorizontalPosition,
        '"WebDBElements".Elements[3].type': adapterJSON.elements[2].type,
        '"WebDBElements".Elements[3].display': adapterJSON.elements[2].display,
        '"WebDBElements".Elements[3].fontSize': adapterJSON.elements[2].fontSize,

        '"WebDBElements".Elements[4].elementId': adapterJSON.elements[3].elementId,
        '"WebDBElements".Elements[4].elementType': adapterJSON.elements[3].elementType,
        '"WebDBElements".Elements[4].elementName': adapterJSON.elements[3].elementName,
        '"WebDBElements".Elements[4].elementSize': adapterJSON.elements[3].elementSize,
        '"WebDBElements".Elements[4].elementMinSize': adapterJSON.elements[3].elementMinSize,
        '"WebDBElements".Elements[4].elementVerticalPosition': adapterJSON.elements[3].elementVerticalPosition,
        '"WebDBElements".Elements[4].elementHorizontalPosition': adapterJSON.elements[3].elementHorizontalPosition,
        '"WebDBElements".Elements[4].type': adapterJSON.elements[3].type,
        '"WebDBElements".Elements[4].display': adapterJSON.elements[3].display,
        '"WebDBElements".Elements[4].fontSize': adapterJSON.elements[3].fontSize,

        '"WebDBElements".Elements[5].elementId': adapterJSON.elements[4].elementId,
        '"WebDBElements".Elements[5].elementType': adapterJSON.elements[4].elementType,
        '"WebDBElements".Elements[5].elementName': adapterJSON.elements[4].elementName,
        '"WebDBElements".Elements[5].elementSize': adapterJSON.elements[4].elementSize,
        '"WebDBElements".Elements[5].elementMinSize': adapterJSON.elements[4].elementMinSize,
        '"WebDBElements".Elements[5].elementVerticalPosition': adapterJSON.elements[4].elementVerticalPosition,
        '"WebDBElements".Elements[5].elementHorizontalPosition': adapterJSON.elements[4].elementHorizontalPosition,
        '"WebDBElements".Elements[5].type': adapterJSON.elements[4].type,
        '"WebDBElements".Elements[5].display': adapterJSON.elements[4].display,
        '"WebDBElements".Elements[5].fontSize': adapterJSON.elements[4].fontSize,

        '"WebDBElements".Elements[6].elementId': adapterJSON.elements[5].elementId,
        '"WebDBElements".Elements[6].elementType': adapterJSON.elements[5].elementType,
        '"WebDBElements".Elements[6].elementName': adapterJSON.elements[5].elementName,
        '"WebDBElements".Elements[6].elementSize': adapterJSON.elements[5].elementSize,
        '"WebDBElements".Elements[6].elementMinSize': adapterJSON.elements[5].elementMinSize,
        '"WebDBElements".Elements[6].elementVerticalPosition': adapterJSON.elements[5].elementVerticalPosition,
        '"WebDBElements".Elements[6].elementHorizontalPosition': adapterJSON.elements[5].elementHorizontalPosition,
        '"WebDBElements".Elements[6].type': adapterJSON.elements[5].type,
        '"WebDBElements".Elements[6].display': adapterJSON.elements[5].display,
        '"WebDBElements".Elements[6].fontSize': adapterJSON.elements[5].fontSize,

        '"WebDBElements".Elements[7].elementId': adapterJSON.elements[6].elementId,
        '"WebDBElements".Elements[7].elementType': adapterJSON.elements[6].elementType,
        '"WebDBElements".Elements[7].elementName': adapterJSON.elements[6].elementName,
        '"WebDBElements".Elements[7].elementSize': adapterJSON.elements[6].elementSize,
        '"WebDBElements".Elements[7].elementMinSize': adapterJSON.elements[6].elementMinSize,
        '"WebDBElements".Elements[7].elementVerticalPosition': adapterJSON.elements[6].elementVerticalPosition,
        '"WebDBElements".Elements[7].elementHorizontalPosition': adapterJSON.elements[6].elementHorizontalPosition,
        '"WebDBElements".Elements[7].type': adapterJSON.elements[6].type,
        '"WebDBElements".Elements[7].display': adapterJSON.elements[6].display,
        '"WebDBElements".Elements[7].fontSize': adapterJSON.elements[6].fontSize,

        '"WebDBElements".Elements[8].elementId': adapterJSON.elements[7].elementId,
        '"WebDBElements".Elements[8].elementType': adapterJSON.elements[7].elementType,
        '"WebDBElements".Elements[8].elementName': adapterJSON.elements[7].elementName,
        '"WebDBElements".Elements[8].elementSize': adapterJSON.elements[7].elementSize,
        '"WebDBElements".Elements[8].elementMinSize': adapterJSON.elements[7].elementMinSize,
        '"WebDBElements".Elements[8].elementVerticalPosition': adapterJSON.elements[7].elementVerticalPosition,
        '"WebDBElements".Elements[8].elementHorizontalPosition': adapterJSON.elements[7].elementHorizontalPosition,
        '"WebDBElements".Elements[8].type': adapterJSON.elements[7].type,
        '"WebDBElements".Elements[8].display': adapterJSON.elements[7].display,
        '"WebDBElements".Elements[8].fontSize': adapterJSON.elements[7].fontSize,

        '"WebDBElements".Elements[9].elementId': adapterJSON.elements[8].elementId,
        '"WebDBElements".Elements[9].elementType': adapterJSON.elements[8].elementType,
        '"WebDBElements".Elements[9].elementName': adapterJSON.elements[8].elementName,
        '"WebDBElements".Elements[9].elementSize': adapterJSON.elements[8].elementSize,
        '"WebDBElements".Elements[9].elementMinSize': adapterJSON.elements[8].elementMinSize,
        '"WebDBElements".Elements[9].elementVerticalPosition': adapterJSON.elements[8].elementVerticalPosition,
        '"WebDBElements".Elements[9].elementHorizontalPosition': adapterJSON.elements[8].elementHorizontalPosition,
        '"WebDBElements".Elements[9].type': adapterJSON.elements[8].type,
        '"WebDBElements".Elements[9].display': adapterJSON.elements[8].display,
        '"WebDBElements".Elements[9].fontSize': adapterJSON.elements[8].fontSize,

        '"WebDBElements".Elements[10].elementId': adapterJSON.elements[9].elementId,
        '"WebDBElements".Elements[10].elementType': adapterJSON.elements[9].elementType,
        '"WebDBElements".Elements[10].elementName': adapterJSON.elements[9].elementName,
        '"WebDBElements".Elements[10].elementSize': adapterJSON.elements[9].elementSize,
        '"WebDBElements".Elements[10].elementMinSize': adapterJSON.elements[9].elementMinSize,
        '"WebDBElements".Elements[10].elementVerticalPosition': adapterJSON.elements[9].elementVerticalPosition,
        '"WebDBElements".Elements[10].elementHorizontalPosition': adapterJSON.elements[9].elementHorizontalPosition,
        '"WebDBElements".Elements[10].type': adapterJSON.elements[9].type,
        '"WebDBElements".Elements[10].display': adapterJSON.elements[9].display,
        '"WebDBElements".Elements[10].fontSize': adapterJSON.elements[9].fontSize,

        '"WebDBElements".Elements[11].elementId': adapterJSON.elements[10].elementId,
        '"WebDBElements".Elements[11].elementType': adapterJSON.elements[10].elementType,
        '"WebDBElements".Elements[11].elementName': adapterJSON.elements[10].elementName,
        '"WebDBElements".Elements[11].elementSize': adapterJSON.elements[10].elementSize,
        '"WebDBElements".Elements[11].elementMinSize': adapterJSON.elements[10].elementMinSize,
        '"WebDBElements".Elements[11].elementVerticalPosition': adapterJSON.elements[10].elementVerticalPosition,
        '"WebDBElements".Elements[11].elementHorizontalPosition': adapterJSON.elements[10].elementHorizontalPosition,
        '"WebDBElements".Elements[11].type': adapterJSON.elements[10].type,
        '"WebDBElements".Elements[11].display': adapterJSON.elements[10].display,
        '"WebDBElements".Elements[11].fontSize': adapterJSON.elements[10].fontSize,

        '"WebDBElements".Elements[12].elementId': adapterJSON.elements[11].elementId,
        '"WebDBElements".Elements[12].elementType': adapterJSON.elements[11].elementType,
        '"WebDBElements".Elements[12].elementName': adapterJSON.elements[11].elementName,
        '"WebDBElements".Elements[12].elementSize': adapterJSON.elements[11].elementSize,
        '"WebDBElements".Elements[12].elementMinSize': adapterJSON.elements[11].elementMinSize,
        '"WebDBElements".Elements[12].elementVerticalPosition': adapterJSON.elements[11].elementVerticalPosition,
        '"WebDBElements".Elements[12].elementHorizontalPosition': adapterJSON.elements[11].elementHorizontalPosition,
        '"WebDBElements".Elements[12].type': adapterJSON.elements[11].type,
        '"WebDBElements".Elements[12].display': adapterJSON.elements[11].display,
        '"WebDBElements".Elements[12].fontSize': adapterJSON.elements[11].fontSize,

        '"WebDBElements".Elements[13].elementId': adapterJSON.elements[12].elementId,
        '"WebDBElements".Elements[13].elementType': adapterJSON.elements[12].elementType,
        '"WebDBElements".Elements[13].elementName': adapterJSON.elements[12].elementName,
        '"WebDBElements".Elements[13].elementSize': adapterJSON.elements[12].elementSize,
        '"WebDBElements".Elements[13].elementMinSize': adapterJSON.elements[12].elementMinSize,
        '"WebDBElements".Elements[13].elementVerticalPosition': adapterJSON.elements[12].elementVerticalPosition,
        '"WebDBElements".Elements[13].elementHorizontalPosition': adapterJSON.elements[12].elementHorizontalPosition,
        '"WebDBElements".Elements[13].type': adapterJSON.elements[12].type,
        '"WebDBElements".Elements[13].display': adapterJSON.elements[12].display,
        '"WebDBElements".Elements[13].fontSize': adapterJSON.elements[12].fontSize,

        '"WebDBElements".Elements[14].elementId': adapterJSON.elements[13].elementId,
        '"WebDBElements".Elements[14].elementType': adapterJSON.elements[13].elementType,
        '"WebDBElements".Elements[14].elementName': adapterJSON.elements[13].elementName,
        '"WebDBElements".Elements[14].elementSize': adapterJSON.elements[13].elementSize,
        '"WebDBElements".Elements[14].elementMinSize': adapterJSON.elements[13].elementMinSize,
        '"WebDBElements".Elements[14].elementVerticalPosition': adapterJSON.elements[13].elementVerticalPosition,
        '"WebDBElements".Elements[14].elementHorizontalPosition': adapterJSON.elements[13].elementHorizontalPosition,
        '"WebDBElements".Elements[14].type': adapterJSON.elements[13].type,
        '"WebDBElements".Elements[14].display': adapterJSON.elements[13].display,
        '"WebDBElements".Elements[14].fontSize': adapterJSON.elements[13].fontSize,

        '"WebDBElements".Elements[15].elementId': adapterJSON.elements[14].elementId,
        '"WebDBElements".Elements[15].elementType': adapterJSON.elements[14].elementType,
        '"WebDBElements".Elements[15].elementName': adapterJSON.elements[14].elementName,
        '"WebDBElements".Elements[15].elementSize': adapterJSON.elements[14].elementSize,
        '"WebDBElements".Elements[15].elementMinSize': adapterJSON.elements[14].elementMinSize,
        '"WebDBElements".Elements[15].elementVerticalPosition': adapterJSON.elements[14].elementVerticalPosition,
        '"WebDBElements".Elements[15].elementHorizontalPosition': adapterJSON.elements[14].elementHorizontalPosition,
        '"WebDBElements".Elements[15].type': adapterJSON.elements[14].type,
        '"WebDBElements".Elements[15].display': adapterJSON.elements[14].display,
        '"WebDBElements".Elements[15].fontSize': adapterJSON.elements[14].fontSize
    };
}