function saveElementsJson() {
    postJson = {
        '"WebDBElements".Elements[1].elementId': adapterJSON.elements[0].elementId,
        '"WebDBElements".Elements[1].elementType': adapterJSON.elements[0].elementType,
        '"WebDBElements".Elements[1].elementName': adapterJSON.elements[0].elementName,
        '"WebDBElements".Elements[1].data': adapterJSON.elements[0].data,
        '"WebDBElements".Elements[1].dataSampleTime': adapterJSON.elements[0].dataSampleTime,
        '"WebDBElements".Elements[1].elementSize': adapterJSON.elements[0].elementSize,
        '"WebDBElements".Elements[1].elementMinSize': adapterJSON.elements[0].elementMinSize,
        '"WebDBElements".Elements[1].elementVerticalPosition': adapterJSON.elements[0].elementVerticalPosition,
        '"WebDBElements".Elements[1].elementHorizontalPosition': adapterJSON.elements[0].elementHorizontalPosition,
        '"WebDBElements".Elements[1].type': adapterJSON.elements[0].type,
        '"WebDBElements".Elements[1].display': adapterJSON.elements[0].display,
        '"WebDBElements".Elements[1].fontSize': adapterJSON.elements[0].fontSize,

        '"WebDBElements".Elements[2].elementId': adapterJSON.elements[1].elementId,
        '"WebDBElements".Elements[2].elementType': adapterJSON.elements[1].elementType,
        '"WebDBElements".Elements[2].elementName': adapterJSON.elements[1].elementName,
        '"WebDBElements".Elements[2].elementSize': adapterJSON.elements[1].elementSize,
        '"WebDBElements".Elements[2].elementMinSize': adapterJSON.elements[1].elementMinSize,
        '"WebDBElements".Elements[2].elementVerticalPosition': adapterJSON.elements[1].elementVerticalPosition,
        '"WebDBElements".Elements[2].elementHorizontalPosition': adapterJSON.elements[1].elementHorizontalPosition,
        '"WebDBElements".Elements[2].data': adapterJSON.elements[1].data,
        '"WebDBElements".Elements[2].dataSampleTime': adapterJSON.elements[1].dataSampleTime,
        '"WebDBElements".Elements[2].type': adapterJSON.elements[1].type,
        '"WebDBElements".Elements[2].display': adapterJSON.elements[1].display,
        '"WebDBElements".Elements[2].fontSize': adapterJSON.elements[1].fontSize,

        '"WebDBElements".Elements[3].elementId': adapterJSON.elements[2].elementId,
        '"WebDBElements".Elements[3].elementType': adapterJSON.elements[2].elementType,
        '"WebDBElements".Elements[3].elementName': adapterJSON.elements[2].elementName,
        '"WebDBElements".Elements[3].elementSize': adapterJSON.elements[2].elementSize,
        '"WebDBElements".Elements[3].elementMinSize': adapterJSON.elements[2].elementMinSize,
        '"WebDBElements".Elements[3].elementVerticalPosition': adapterJSON.elements[2].elementVerticalPosition,
        '"WebDBElements".Elements[3].elementHorizontalPosition': adapterJSON.elements[2].elementHorizontalPosition,
        '"WebDBElements".Elements[3].data': adapterJSON.elements[2].data,
        '"WebDBElements".Elements[3].dataSampleTime': adapterJSON.elements[2].dataSampleTime,
        '"WebDBElements".Elements[3].type': adapterJSON.elements[2].type,
        '"WebDBElements".Elements[3].display': adapterJSON.elements[2].display,
        '"WebDBElements".Elements[3].fontSize': adapterJSON.elements[2].fontSize,

        '"WebDBElements".Elements[4].elementId': adapterJSON.elements[3].elementId,
        '"WebDBElements".Elements[4].elementType': adapterJSON.elements[3].elementType,
        '"WebDBElements".Elements[4].elementName': adapterJSON.elements[3].elementName,
        '"WebDBElements".Elements[4].elementSize': adapterJSON.elements[3].elementSize,
        '"WebDBElements".Elements[4].elementMinSize': adapterJSON.elements[3].elementMinSize,
        '"WebDBElements".Elements[4].elementVerticalPosition': adapterJSON.elements[3].elementVerticalPosition,
        '"WebDBElements".Elements[4].elementHorizontalPosition': adapterJSON.elements[3].elementHorizontalPosition,
        '"WebDBElements".Elements[4].data': adapterJSON.elements[3].data,
        '"WebDBElements".Elements[4].dataSampleTime': adapterJSON.elements[3].dataSampleTime,
        '"WebDBElements".Elements[4].type': adapterJSON.elements[3].type,
        '"WebDBElements".Elements[4].display': adapterJSON.elements[3].display,
        '"WebDBElements".Elements[4].fontSize': adapterJSON.elements[3].fontSize,

        '"WebDBElements".Elements[5].elementId': adapterJSON.elements[4].elementId,
        '"WebDBElements".Elements[5].elementType': adapterJSON.elements[4].elementType,
        '"WebDBElements".Elements[5].elementName': adapterJSON.elements[4].elementName,
        '"WebDBElements".Elements[5].elementSize': adapterJSON.elements[4].elementSize,
        '"WebDBElements".Elements[5].elementMinSize': adapterJSON.elements[4].elementMinSize,
        '"WebDBElements".Elements[5].elementVerticalPosition': adapterJSON.elements[4].elementVerticalPosition,
        '"WebDBElements".Elements[5].elementHorizontalPosition': adapterJSON.elements[4].elementHorizontalPosition,
        '"WebDBElements".Elements[5].data': adapterJSON.elements[4].data,
        '"WebDBElements".Elements[5].dataSampleTime': adapterJSON.elements[4].dataSampleTime,
        '"WebDBElements".Elements[5].type': adapterJSON.elements[4].type,
        '"WebDBElements".Elements[5].display': adapterJSON.elements[4].display,
        '"WebDBElements".Elements[5].fontSize': adapterJSON.elements[4].fontSize,

        '"WebDBElements".Elements[6].elementId': adapterJSON.elements[5].elementId,
        '"WebDBElements".Elements[6].elementType': adapterJSON.elements[5].elementType,
        '"WebDBElements".Elements[6].elementName': adapterJSON.elements[5].elementName,
        '"WebDBElements".Elements[6].elementSize': adapterJSON.elements[5].elementSize,
        '"WebDBElements".Elements[6].elementMinSize': adapterJSON.elements[5].elementMinSize,
        '"WebDBElements".Elements[6].elementVerticalPosition': adapterJSON.elements[5].elementVerticalPosition,
        '"WebDBElements".Elements[6].elementHorizontalPosition': adapterJSON.elements[5].elementHorizontalPosition,
        '"WebDBElements".Elements[6].data': adapterJSON.elements[5].data,
        '"WebDBElements".Elements[6].dataSampleTime': adapterJSON.elements[5].dataSampleTime,
        '"WebDBElements".Elements[6].type': adapterJSON.elements[5].type,
        '"WebDBElements".Elements[6].display': adapterJSON.elements[5].display,
        '"WebDBElements".Elements[6].fontSize': adapterJSON.elements[5].fontSize,

        '"WebDBElements".Elements[7].elementId': adapterJSON.elements[6].elementId,
        '"WebDBElements".Elements[7].elementType': adapterJSON.elements[6].elementType,
        '"WebDBElements".Elements[7].elementName': adapterJSON.elements[6].elementName,
        '"WebDBElements".Elements[7].elementSize': adapterJSON.elements[6].elementSize,
        '"WebDBElements".Elements[7].elementMinSize': adapterJSON.elements[6].elementMinSize,
        '"WebDBElements".Elements[7].elementVerticalPosition': adapterJSON.elements[6].elementVerticalPosition,
        '"WebDBElements".Elements[7].elementHorizontalPosition': adapterJSON.elements[6].elementHorizontalPosition,
        '"WebDBElements".Elements[7].data': adapterJSON.elements[6].data,
        '"WebDBElements".Elements[7].dataSampleTime': adapterJSON.elements[6].dataSampleTime,
        '"WebDBElements".Elements[7].type': adapterJSON.elements[6].type,
        '"WebDBElements".Elements[7].display': adapterJSON.elements[6].display,
        '"WebDBElements".Elements[7].fontSize': adapterJSON.elements[6].fontSize,

        '"WebDBElements".Elements[8].elementId': adapterJSON.elements[7].elementId,
        '"WebDBElements".Elements[8].elementType': adapterJSON.elements[7].elementType,
        '"WebDBElements".Elements[8].elementName': adapterJSON.elements[7].elementName,
        '"WebDBElements".Elements[8].elementSize': adapterJSON.elements[7].elementSize,
        '"WebDBElements".Elements[8].elementMinSize': adapterJSON.elements[7].elementMinSize,
        '"WebDBElements".Elements[8].elementVerticalPosition': adapterJSON.elements[7].elementVerticalPosition,
        '"WebDBElements".Elements[8].elementHorizontalPosition': adapterJSON.elements[7].elementHorizontalPosition,
        '"WebDBElements".Elements[8].data': adapterJSON.elements[7].data,
        '"WebDBElements".Elements[8].dataSampleTime': adapterJSON.elements[7].dataSampleTime,
        '"WebDBElements".Elements[8].type': adapterJSON.elements[7].type,
        '"WebDBElements".Elements[8].display': adapterJSON.elements[7].display,
        '"WebDBElements".Elements[8].fontSize': adapterJSON.elements[7].fontSize,

        '"WebDBElements".Elements[9].elementId': adapterJSON.elements[8].elementId,
        '"WebDBElements".Elements[9].elementType': adapterJSON.elements[8].elementType,
        '"WebDBElements".Elements[9].elementName': adapterJSON.elements[8].elementName,
        '"WebDBElements".Elements[9].elementSize': adapterJSON.elements[8].elementSize,
        '"WebDBElements".Elements[9].elementMinSize': adapterJSON.elements[8].elementMinSize,
        '"WebDBElements".Elements[9].elementVerticalPosition': adapterJSON.elements[8].elementVerticalPosition,
        '"WebDBElements".Elements[9].elementHorizontalPosition': adapterJSON.elements[8].elementHorizontalPosition,
        '"WebDBElements".Elements[9].data': adapterJSON.elements[8].data,
        '"WebDBElements".Elements[9].dataSampleTime': adapterJSON.elements[8].dataSampleTime,
        '"WebDBElements".Elements[9].type': adapterJSON.elements[8].type,
        '"WebDBElements".Elements[9].display': adapterJSON.elements[8].display,
        '"WebDBElements".Elements[9].fontSize': adapterJSON.elements[8].fontSize,

        '"WebDBElements".Elements[10].elementId': adapterJSON.elements[9].elementId,
        '"WebDBElements".Elements[10].elementType': adapterJSON.elements[9].elementType,
        '"WebDBElements".Elements[10].elementName': adapterJSON.elements[9].elementName,
        '"WebDBElements".Elements[10].elementSize': adapterJSON.elements[9].elementSize,
        '"WebDBElements".Elements[10].elementMinSize': adapterJSON.elements[9].elementMinSize,
        '"WebDBElements".Elements[10].elementVerticalPosition': adapterJSON.elements[9].elementVerticalPosition,
        '"WebDBElements".Elements[10].elementHorizontalPosition': adapterJSON.elements[9].elementHorizontalPosition,
        '"WebDBElements".Elements[10].data': adapterJSON.elements[9].data,
        '"WebDBElements".Elements[10].dataSampleTime': adapterJSON.elements[9].dataSampleTime,
        '"WebDBElements".Elements[10].type': adapterJSON.elements[9].type,
        '"WebDBElements".Elements[10].display': adapterJSON.elements[9].display,
        '"WebDBElements".Elements[10].fontSize': adapterJSON.elements[9].fontSize
    };
}